import React, { useState } from 'react';
import { useApp } from '../context/AppContext';
import { HermesMemoryType, HermesCandidateRule } from '../types';
import { 
  Brain, 
  Layers, 
  CheckCircle2, 
  XCircle, 
  ShieldAlert, 
  Lock, 
  Sparkles, 
  BookOpen, 
  MessageSquare, 
  Sliders,
  Check,
  ChevronRight,
  TrendingUp,
  AlertCircle
} from 'lucide-react';

export const HermesGovernanceView: React.FC = () => {
  const { memories, candidateRules, updateCandidateRuleStatus } = useApp();
  const [selectedMemoryType, setSelectedMemoryType] = useState<HermesMemoryType | 'ALL'>('ALL');
  const [activeTab, setActiveTab] = useState<'MEMORIES' | 'CANDIDATE_RULES'>('CANDIDATE_RULES');

  const filteredMemories = memories.filter(m => {
    if (selectedMemoryType === 'ALL') return true;
    return m.memory_type === selectedMemoryType;
  });

  return (
    <div className="space-y-4">
      {/* Header Banner */}
      <div className="bg-[#0F172A] border border-[#1E293B] rounded-xs p-4 flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <div className="w-2 h-2 bg-purple-400 rotate-45"></div>
            <span className="text-[10px] font-mono uppercase tracking-widest text-purple-400 font-bold">
              [ NOUS_RESEARCH_HERMES // INSTITUTIONAL_MEMORY_LAYER ]
            </span>
          </div>
          <h2 className="text-xl font-light text-white mt-1 font-mono tracking-tight">
            Hermes Self-Learning Engine & Multi-Tier Governance
          </h2>
          <p className="text-xs text-slate-400 mt-0.5 max-w-3xl leading-relaxed">
            Continuous institutional learning across investigations. Synthesizes analyst overrides into candidate heuristics with strict MLRO human-in-the-loop signoff.
          </p>
        </div>

        <div className="flex items-center gap-2 shrink-0 font-mono text-xs">
          <div className="px-3 py-1.5 bg-[#0A0C10] border border-purple-500/40 rounded-xs text-purple-300">
            <span>MEMORIES INDEXED: </span>
            <strong className="text-white">{memories.length}</strong>
          </div>
          <div className="px-3 py-1.5 bg-[#0A0C10] border border-amber-500/40 rounded-xs text-amber-300">
            <span>PROPOSED RULES: </span>
            <strong className="text-white">{candidateRules.filter(r => r.status === 'PROPOSED').length}</strong>
          </div>
        </div>
      </div>

      {/* Regulatory Boundary Card */}
      <div className="bg-amber-950/20 border border-amber-500/40 rounded-xs p-3 flex items-start gap-3">
        <Lock className="w-4 h-4 text-amber-400 shrink-0 mt-0.5" />
        <div className="text-xs">
          <span className="font-bold text-amber-300 font-mono uppercase block text-[11px]">
            Statutory Guardrail: No Autonomous Heuristic Deployment
          </span>
          <p className="text-slate-300 font-sans mt-0.5 text-[11px] leading-relaxed">
            Hermes agent memory is strictly separated into advisory and candidate proposal tiers. Under FinCEN and OCC model validation standards, no candidate rule or weight adjustment is ever activated in production without authenticated compliance officer approval.
          </p>
        </div>
      </div>

      {/* Sub-Nav Tabs */}
      <div className="flex items-center gap-2 border-b border-[#1E293B] pb-2 font-mono text-xs">
        <button
          onClick={() => setActiveTab('CANDIDATE_RULES')}
          className={`px-3 py-1.5 rounded-xs transition flex items-center gap-2 ${
            activeTab === 'CANDIDATE_RULES'
              ? 'bg-cyan-950 border border-cyan-400 text-cyan-300 font-bold'
              : 'bg-[#0A0C10] border border-[#1E293B] text-slate-400 hover:text-white'
          }`}
        >
          <Sliders className="w-3.5 h-3.5 text-cyan-400" />
          <span>CANDIDATE_HEURISTICS_QUEUE ({candidateRules.length})</span>
        </button>

        <button
          onClick={() => setActiveTab('MEMORIES')}
          className={`px-3 py-1.5 rounded-xs transition flex items-center gap-2 ${
            activeTab === 'MEMORIES'
              ? 'bg-purple-950 border border-purple-400 text-purple-300 font-bold'
              : 'bg-[#0A0C10] border border-[#1E293B] text-slate-400 hover:text-white'
          }`}
        >
          <Brain className="w-3.5 h-3.5 text-purple-400" />
          <span>MULTI-TIER_MEMORY_INSPECTION ({memories.length})</span>
        </button>
      </div>

      {/* VIEW 1: Candidate Heuristics Queue */}
      {activeTab === 'CANDIDATE_RULES' && (
        <div className="space-y-3 font-mono text-xs">
          <div className="bg-[#0A0C10] border border-[#1E293B] rounded-xs p-3 flex items-center justify-between text-[11px]">
            <span className="text-slate-400">
              Heuristics generated by Hermes from analyst overrides and recurrent pattern reflections:
            </span>
            <span className="text-cyan-400">
              100% REVERSIBLE & AUDITABLE
            </span>
          </div>

          <div className="space-y-3">
            {candidateRules.map((rule) => {
              const isProposed = rule.status === 'PROPOSED';
              const isApproved = rule.status === 'APPROVED';
              const isDeployed = rule.status === 'DEPLOYED';
              const isRejected = rule.status === 'REJECTED';

              return (
                <div 
                  key={rule.id}
                  className="bg-[#0A0C10] border border-[#1E293B] rounded-xs p-4 space-y-3 hover:border-slate-700 transition"
                >
                  <div className="flex flex-col md:flex-row md:items-center justify-between gap-2">
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-white text-sm">
                        {rule.title}
                      </span>
                      <span className={`text-[9px] px-2 py-0.5 rounded-xs font-bold ${
                        isProposed
                          ? 'bg-amber-950 text-amber-300 border border-amber-800'
                          : isApproved || isDeployed
                          ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                          : 'bg-rose-950 text-rose-300 border border-rose-800'
                      }`}>
                        {rule.status}
                      </span>
                    </div>

                    <div className="text-[10px] text-slate-500">
                      Proposed: {rule.proposed_at.substring(0, 16).replace('T', ' ')}
                    </div>
                  </div>

                  <p className="text-slate-300 font-sans text-xs leading-relaxed">
                    {rule.description}
                  </p>

                  {/* Pseudo-Code Logic Box */}
                  <div className="p-2.5 bg-[#0F172A] border border-[#1E293B] rounded-xs text-[11px] text-cyan-300 font-mono">
                    <span className="text-slate-500 block text-[9px] uppercase">Synthesized Rule Logic:</span>
                    <code>{rule.rule_logic}</code>
                  </div>

                  {/* Metrics & Rationale */}
                  <div className="flex flex-wrap items-center justify-between gap-2 pt-2 border-t border-[#1E293B] text-[11px]">
                    <div className="flex items-center gap-3 text-slate-400">
                      <span>Impact: <strong className="text-white">{rule.impact_cases_count} cases</strong></span>
                      <span className="text-slate-600">•</span>
                      <span>Rationale: <span className="text-slate-300 italic">{rule.rationale}</span></span>
                      {rule.reviewed_by && (
                        <>
                          <span className="text-slate-600">•</span>
                          <span className="text-emerald-400 font-semibold">Signed off by: {rule.reviewed_by}</span>
                        </>
                      )}
                    </div>

                    {/* Action Controls for Compliance Lead */}
                    {isProposed && (
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => updateCandidateRuleStatus(rule.id, 'APPROVED')}
                          className="px-3 py-1 bg-emerald-600 hover:bg-emerald-500 text-white font-bold rounded-xs transition text-xs flex items-center gap-1"
                        >
                          <Check className="w-3.5 h-3.5" />
                          <span>APPROVE_HEURISTIC</span>
                        </button>
                        <button
                          onClick={() => updateCandidateRuleStatus(rule.id, 'REJECTED')}
                          className="px-3 py-1 bg-[#0F172A] hover:bg-rose-950 text-rose-400 hover:text-rose-300 border border-rose-900 rounded-xs transition text-xs"
                        >
                          REJECT
                        </button>
                      </div>
                    )}

                    {isApproved && (
                      <button
                        onClick={() => updateCandidateRuleStatus(rule.id, 'DEPLOYED')}
                        className="px-3 py-1 bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-bold rounded-xs transition text-xs flex items-center gap-1"
                      >
                        <TrendingUp className="w-3.5 h-3.5" />
                        <span>DEPLOY_TO_PRODUCTION</span>
                      </button>
                    )}

                    {isDeployed && (
                      <span className="text-[10px] text-emerald-400 font-bold flex items-center gap-1">
                        <CheckCircle2 className="w-3.5 h-3.5" />
                        LIVE_IN_RULES_ENGINE
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* VIEW 2: Multi-Tier Memory Inspection */}
      {activeTab === 'MEMORIES' && (
        <div className="space-y-4 font-mono text-xs">
          {/* Memory Type Filter Buttons */}
          <div className="flex flex-wrap items-center gap-2">
            {(['ALL', 'EPISODIC', 'SEMANTIC', 'SKILL', 'FEEDBACK'] as const).map((tier) => (
              <button
                key={tier}
                onClick={() => setSelectedMemoryType(tier)}
                className={`px-3 py-1 rounded-xs transition text-xs ${
                  selectedMemoryType === tier
                    ? 'bg-purple-950 border border-purple-400 text-purple-300 font-bold'
                    : 'bg-[#0A0C10] border border-[#1E293B] text-slate-400 hover:text-white'
                }`}
              >
                {tier} MEMORY
              </button>
            ))}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {filteredMemories.map((mem) => (
              <div
                key={mem.id}
                className="bg-[#0A0C10] border border-[#1E293B] rounded-xs p-3.5 space-y-2 hover:border-slate-700 transition flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between pb-1.5 border-b border-[#1E293B]">
                    <span className={`text-[9px] px-1.5 py-0.2 rounded-xs font-bold ${
                      mem.memory_type === 'FEEDBACK'
                        ? 'bg-amber-950 text-amber-300 border border-amber-800'
                        : mem.memory_type === 'EPISODIC'
                        ? 'bg-cyan-950 text-cyan-300 border border-cyan-800'
                        : mem.memory_type === 'SKILL'
                        ? 'bg-emerald-950 text-emerald-300 border border-emerald-800'
                        : 'bg-purple-950 text-purple-300 border border-purple-800'
                    }`}>
                      {mem.memory_type}
                    </span>
                    <span className="text-[10px] text-slate-500">
                      {Math.round(mem.confidence * 100)}% Confidence
                    </span>
                  </div>

                  <h4 className="text-white font-bold text-xs mt-2">
                    {mem.title}
                  </h4>

                  <p className="text-slate-300 font-sans text-[11px] leading-relaxed mt-1">
                    {mem.content}
                  </p>
                </div>

                <div className="pt-2 border-t border-[#1E293B] flex flex-wrap items-center justify-between gap-1 text-[10px] text-slate-500">
                  <div className="flex flex-wrap gap-1">
                    {mem.tags.map((t, idx) => (
                      <span key={idx} className="bg-[#0F172A] px-1 py-0.2 rounded text-slate-400">
                        #{t}
                      </span>
                    ))}
                  </div>
                  <span>Ref: {mem.case_reference || 'SYSTEM'}</span>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
